name: embraceprom
favicon: null
layout_spectrum: 0.9424014752730727
typography_spectrum: 0.38252
title: PROM
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fcf8f9'
    - '#92000c'
    - '#707070'
    - '#c2c2c2'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
